"""Email publishing helpers for the News To Me pipeline."""

from __future__ import annotations

import json
import os
import smtplib
from dataclasses import dataclass
from email.message import EmailMessage
from pathlib import Path
from typing import Any


@dataclass
class EmailConfig:
    """Runtime configuration for SMTP email delivery."""

    sender: str = os.getenv('GMAIL_SENDER', '')
    password: str = os.getenv('GMAIL_APP_PASSWORD', '')
    recipient: str = os.getenv('EMAIL_TO', 'bhargavbangalorevmurthy@gmail.com')
    smtp_host: str = os.getenv('SMTP_HOST', 'smtp.gmail.com')
    smtp_port: int = int(os.getenv('SMTP_PORT', '465'))


class EmailPublisher:
    """Render and optionally send an edition email."""

    def __init__(self, config: EmailConfig | None = None) -> None:
        self.config = config or EmailConfig()

    def build_subject(self, edition: dict[str, Any]) -> str:
        """Build the email subject for an edition."""
        return f"News To Me, {edition['date']}"

    def build_text(self, edition: dict[str, Any]) -> str:
        """Render a plain-text email body from the edition."""
        lines = [
            'News To Me',
            '',
            f"Date: {edition['date']}",
            '',
            'TLDR',
        ]
        for item in edition['tldr']:
            lines.append(f"- {item['headline']}: {item['summary']}")
        lines.extend([
            '',
            'Sections included:',
            f"- News regions: {', '.join(edition['news'].keys())}",
            f"- Biz/Tech articles: {len(edition['biztech']['articles'])}",
            f"- Growth: {edition['growth']['title']}",
            f"- Knowledge: {edition['knowledge']['title']}",
            f"- Riddle: {edition['fun']['riddle']['question']}",
        ])
        return '\n'.join(lines)

    def build_html(self, edition: dict[str, Any]) -> str:
        """Render a simple HTML email body from the edition."""
        tldr_items = ''.join(
            f"<li><strong>{item['headline']}</strong><br>{item['summary']}</li>"
            for item in edition['tldr']
        )
        return f"""<!doctype html>
<html lang='en'>
  <body style='margin:0;background:#f8fafc;color:#0f172a;font-family:Arial,sans-serif;'>
    <div style='max-width:720px;margin:24px auto;padding:24px;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;'>
      <p style='margin:0 0 8px;font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:#64748b;'>News To Me</p>
      <h1 style='margin:0 0 8px;font-size:28px;line-height:1.2;'>Your Morning Paper</h1>
      <p style='margin:0 0 20px;color:#475569;'>{edition['date']}</p>
      <h2 style='margin:0 0 10px;font-size:18px;'>TLDR</h2>
      <ul style='margin:0 0 20px;padding-left:20px;color:#334155;line-height:1.6;'>
        {tldr_items}
      </ul>
      <p style='margin:0 0 16px;color:#334155;line-height:1.6;'><strong>Growth:</strong> {edition['growth']['title']}</p>
      <p style='margin:0 0 16px;color:#334155;line-height:1.6;'><strong>Knowledge:</strong> {edition['knowledge']['title']}</p>
      <p style='margin:0;color:#64748b;font-size:13px;line-height:1.5;'>Generated by the News To Me pipeline.</p>
    </div>
  </body>
</html>"""

    def send(self, edition: dict[str, Any]) -> None:
        """Send the edition over SMTP."""
        if not self.config.sender or not self.config.password:
            raise RuntimeError('GMAIL_SENDER and GMAIL_APP_PASSWORD are required for email delivery')

        message = EmailMessage()
        message['Subject'] = self.build_subject(edition)
        message['From'] = self.config.sender
        message['To'] = self.config.recipient
        message.set_content(self.build_text(edition))
        message.add_alternative(self.build_html(edition), subtype='html')

        with smtplib.SMTP_SSL(self.config.smtp_host, self.config.smtp_port) as server:
            server.login(self.config.sender, self.config.password)
            server.send_message(message)

    def write_preview(self, edition: dict[str, Any], output_path: str | Path) -> Path:
        """Write a local JSON preview of the outbound email payload."""
        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            'subject': self.build_subject(edition),
            'to': self.config.recipient,
            'text': self.build_text(edition),
            'html': self.build_html(edition),
        }
        output.write_text(json.dumps(payload, indent=2))
        return output
